In [10]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [8]:
x = np.random.rand(100, 3)
print(x)

[[0.25124929 0.83374253 0.02604257]
 [0.26342681 0.55236039 0.74200789]
 [0.1341873  0.28025075 0.51420231]
 [0.47418847 0.65045105 0.90246174]
 [0.39613013 0.22226867 0.48306145]
 [0.28388012 0.96404698 0.33979701]
 [0.55442854 0.77655175 0.18079063]
 [0.4711549  0.64794376 0.74969781]
 [0.98791611 0.94753039 0.85861482]
 [0.36946541 0.37282188 0.41348482]
 [0.53100303 0.01122079 0.40982509]
 [0.48897448 0.99878169 0.35894484]
 [0.7115064  0.00201526 0.19666571]
 [0.55876351 0.53346802 0.76750912]
 [0.6094606  0.59085944 0.20430256]
 [0.80863781 0.83602779 0.31114996]
 [0.04371033 0.33529103 0.03989082]
 [0.72443714 0.18606849 0.51402516]
 [0.79705003 0.50680569 0.91412396]
 [0.46822634 0.37903193 0.24767815]
 [0.70182171 0.79056459 0.58211229]
 [0.25231709 0.4493004  0.75010842]
 [0.37356086 0.02167995 0.89253646]
 [0.45506672 0.20524756 0.96858459]
 [0.56408528 0.34256783 0.17928336]
 [0.08992436 0.2409057  0.45143723]
 [0.22058903 0.78046889 0.6552225 ]
 [0.31141112 0.88359469 0.60

In [13]:
import lidario as lio

# Translate a raster to a numpy point cloud.
translator = lio.Translator("geotiff", "np")
tif_file_path = "./Data/pos_0/MDA-MB-468_4-colour_EGF_B10_1nM_posXY0_channels_t0_posZ0_colour1_locImage.tif"
point_cloud = translator.translate(tif_file_path)

point_cloud

/opt/conda/lib/python3.11/site-packages/rasterio/__init__.py:304: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)


array([[5.000e-01, 5.000e-01, 0.000e+00],
       [1.500e+00, 5.000e-01, 0.000e+00],
       [2.500e+00, 5.000e-01, 0.000e+00],
       ...,
       [4.255e+02, 6.835e+02, 0.000e+00],
       [4.265e+02, 6.835e+02, 0.000e+00],
       [4.275e+02, 6.835e+02, 0.000e+00]])